name: Update Rules

on:
  push:
    paths:
      - 'mosdns.txt'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache downloaded files
        uses: actions/cache@v3
        with:
          path: ~/.cache/rules
          key: ${{ hashFiles('mosdns.txt') }}-rules-${{ github.run_id }}
          restore-keys: |
            ${{ hashFiles('mosdns.txt') }}-rules-

      - name: Install requests
        run: pip install requests

      - name: Process rules
        run: |
          python - <<EOF
          import os
          import requests
          from collections import OrderedDict, defaultdict

          os.makedirs('mosdns', exist_ok=True)
          os.makedirs('~/.cache/rules', exist_ok=True)
          rules_by_name = defaultdict(list)
          with open('mosdns.txt', 'r') as f:
              for line in f:
                  name, url = line.strip().split(' ', 1)
                  rules_by_name[name].append(url)

          for name, urls in rules_by_name.items():
              output_file = f"mosdns/{name}.txt"
              unique_rules = OrderedDict()
              
              for i, url in enumerate(urls):
                  cache_file = f"~/.cache/rules/{name}_{i}.list"
                  if os.path.exists(cache_file):
                      with open(cache_file, 'r') as f:
                          content = f.read()
                  else:
                      response = requests.get(url)
                      content = response.text
                      with open(cache_file, 'w') as f:
                          f.write(content)
                  
                  for line in content.splitlines():
                      if not line.strip().startswith('#'):
                          modified_line = line.replace('DOMAIN-SUFFIX,', 'full:') \
                                            .replace('DOMAIN,', 'domain:') \
                                            .replace('DOMAIN-KEYWORD,', 'keyword:') \
                                            .strip()
                          if modified_line:
                              unique_rules[modified_line] = None
              
              with open(output_file, 'w') as outfile:
                  for rule_line in unique_rules.keys():
                      outfile.write(rule_line + '\n')
          EOF

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add mosdns/*.txt
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          else
            git commit -m "Update rules from mosdns.txt"
            git push
          fi
