name: Update Rules

on:
  push:
    paths:
      - 'mosdns.txt'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Process rules
        run: |
          python - <<EOF
          import os
          import subprocess
          from collections import OrderedDict

          # 创建 mosdns 目录
          os.makedirs('mosdns', exist_ok=True)

          # 读取 mosdns.txt 并保持顺序
          rules = []
          with open('mosdns.txt', 'r') as f:
              for line in f:
                  name, url = line.strip().split(' ', 1)
                  rules.append((name, url))

          # 使用 OrderedDict 来保持顺序并去重
          rule_dict = OrderedDict()

          # 处理每个规则
          for name, url in rules:
              output_file = f"mosdns/{name}.txt"
              temp_file = f"{name}_{url.split('/')[-1]}.list"
              subprocess.run(['curl', '-o', temp_file, url], check=True)
              
              with open(temp_file, 'r') as infile:
                  for line in infile:
                      if not line.strip().startswith('#'):
                          modified_line = line.replace('DOMAIN-SUFFIX,', 'full:') \
                                            .replace('DOMAIN,', 'domain:') \
                                            .replace('DOMAIN-KEYWORD,', 'keyword:') \
                                            .strip()
                          if modified_line:
                              # 使用 OrderedDict 按顺序存储
                              rule_dict[modified_line] = None
              
              os.remove(temp_file)
          
          # 写入合并后的规则到一个文件
          for name, _ in rules[:1]:  # 只取第一个 name，因为所有 URL 都属于 ChinaList
              output_file = f"mosdns/{name}.txt"
              with open(output_file, 'w') as outfile:
                  for rule_line in rule_dict.keys():
                      outfile.write(rule_line + '\n')
          EOF

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add mosdns/*.txt
          git commit -m "Update rules from mosdns.txt" || echo "No changes to commit"
          git push
