name: Process to Surge

on:
  push:
    branches:
      - main
    paths:
      - 'custom/*.txt'  # 当 custom/ 下的 .txt 文件变动时触发
  pull_request:
    branches:
      - main
    paths:
      - 'custom/*.txt'  # 当 custom/ 下的 .txt 文件变动时触发
  workflow_dispatch:

jobs:
  process-files:
    name: Process TXT Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Create surge Directory
        run: mkdir -p surge

      - name: Debug Input Files
        run: |
          echo "Listing custom directory contents:"
          ls -l custom/ || echo "No files in custom/"
          echo "Input file contents:"
          cat custom/*.txt || echo "No txt files found"

      - name: Process TXT Files
        run: |
          for file in custom/*.txt; do
            [ -f "$file" ] || continue
            echo "Processing $file"
            temp_file=$(mktemp)
            prefix=""
            while IFS= read -r line || [ -n "$line" ]; do
              if [[ -z "$line" || "$line" =~ ^#.* ]]; then
                [[ "$line" =~ ^#域匹配.* ]] && prefix="DOMAIN-SUFFIX,"
                [[ "$line" =~ ^#完整匹配.* ]] && prefix="DOMAIN,"
                [[ "$line" =~ ^#关键字匹配.* ]] && prefix="DOMAIN-KEYWORD,"
                echo "$line" >> "$temp_file"
                continue
              fi
              if [[ "$line" =~ ^(DOMAIN-SUFFIX,|DOMAIN,|DOMAIN-KEYWORD,).* ]]; then
                echo "$line" >> "$temp_file"
              elif [[ -n "$prefix" ]]; then
                echo "${prefix}${line}" >> "$temp_file"
              else
                echo "$line" >> "$temp_file"
              fi
            done < "$file"
            filename=$(basename "$file" .txt).list  # 将 .txt 替换为 .list
            mv "$temp_file" "surge/$filename"
            echo "Output file contents:"
            cat "surge/$filename"
          done

      - name: Commit Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add surge/*.list  # 更新为添加 .list 文件
          git commit -m "Process and move TXT files to surge as .list" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}