name: 规则自动化更新

on:
  push:
    paths:
      - 'custom/**'
      - 'rules.txt'
      - 'main.py'
      - 'mihomo-core'
  schedule:
    - cron: '0 19 * * *' # UTC 19:00 = 北京时间 03:00
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: 安装依赖
        run: pip install requests

      - name: 权限与环境检查
        run: |
          chmod +x ./mihomo-core
          # 检查是否存在同名冲突文件
          if [ -f "mihomo" ]; then rm -f mihomo; fi 

      - name: 执行转换
        run: python main.py

      - name: 推送更改
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff-index --quiet HEAD || git commit -m "Update Rules $(date +'%Y-%m-%d %H:%M')"
          git push